name: praktikum_10
description: A new Flutter project

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7
  # Tambahkan dependency lain di sini

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
